version: '3.8'

services:
  db:
    container_name: PostgreSQL
    image: postgres:16.0
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./backend/test.sql:/docker-entrypoint-initdb.d/db.sql
  
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:8.5
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - ./backend/servers.json:/pgadmin4/servers.json